/*
 * AttJframe.java
 *
 * Created on __DATE__, __TIME__
 */

package jfram;

/**
 *
 * @author  __USER__
 */
public class AttJframe extends javax.swing.JFrame {

	/** Creates new form AttJframe */
	public AttJframe() {
		initComponents();
	}

	/** This method is called from within the constructor to
	 * initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is
	 * always regenerated by the Form Editor.
	 */
	//GEN-BEGIN:initComponents
	// <editor-fold defaultstate="collapsed" desc="Generated Code">
	private void initComponents() {

		label1 = new java.awt.Label();
		wangwangId = new java.awt.TextField();
		label2 = new java.awt.Label();
		label3 = new java.awt.Label();
		label4 = new java.awt.Label();
		weixinId = new java.awt.TextField();
		mobileId = new java.awt.TextField();
		searchButton = new java.awt.Button();
		showResult = new java.awt.TextArea();
		label5 = new java.awt.Label();
		jLabel1 = new javax.swing.JLabel();
		excelPath = new java.awt.TextField();
		excelpushButton = new java.awt.Button();

		setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

		label1.setFont(new java.awt.Font("Dialog", 1, 18));
		label1.setForeground(new java.awt.Color(102, 102, 0));
		label1.setText("\u6587\u672c\u67e5\u91cd");

		label2.setFont(new java.awt.Font("Dialog", 1, 14));
		label2.setText("\u65fa\u65fa\u53f7");

		label3.setFont(new java.awt.Font("Dialog", 1, 14));
		label3.setText("\u5fae\u4fe1\u53f7");

		label4.setFont(new java.awt.Font("Dialog", 1, 14));
		label4.setText("\u624b\u673a\u53f7");

		searchButton.setFont(new java.awt.Font("Dialog", 1, 14));
		searchButton.setForeground(new java.awt.Color(255, 153, 153));
		searchButton.setLabel("\u67e5\u8be2");

		label5.setText("\u67e5\u8be2\u7ed3\u679c");

		jLabel1.setText("\u9009\u62e9\u6587\u4ef6");

		excelPath.setText("\u9009\u62e9\u6587\u4ef6\u76ee\u6807excel");

		excelpushButton.setFont(new java.awt.Font("Dialog", 1, 14));
		excelpushButton.setLabel("\u9009\u62e9");

		org.jdesktop.layout.GroupLayout layout = new org.jdesktop.layout.GroupLayout(
				getContentPane());
		getContentPane().setLayout(layout);
		layout.setHorizontalGroup(layout
				.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
				.add(layout
						.createSequentialGroup()
						.add(79, 79, 79)
						.add(layout
								.createParallelGroup(
										org.jdesktop.layout.GroupLayout.LEADING)
								.add(label5,
										org.jdesktop.layout.GroupLayout.PREFERRED_SIZE,
										org.jdesktop.layout.GroupLayout.DEFAULT_SIZE,
										org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
								.add(label2,
										org.jdesktop.layout.GroupLayout.PREFERRED_SIZE,
										org.jdesktop.layout.GroupLayout.DEFAULT_SIZE,
										org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
								.add(jLabel1))
						.add(layout
								.createParallelGroup(
										org.jdesktop.layout.GroupLayout.LEADING)
								.add(layout
										.createSequentialGroup()
										.addPreferredGap(
												org.jdesktop.layout.LayoutStyle.RELATED)
										.add(showResult,
												org.jdesktop.layout.GroupLayout.DEFAULT_SIZE,
												647, Short.MAX_VALUE))
								.add(layout
										.createSequentialGroup()
										.add(15, 15, 15)
										.add(layout
												.createParallelGroup(
														org.jdesktop.layout.GroupLayout.LEADING)
												.add(layout
														.createSequentialGroup()
														.add(excelPath,
																org.jdesktop.layout.GroupLayout.PREFERRED_SIZE,
																245,
																org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
														.add(51, 51, 51)
														.add(excelpushButton,
																org.jdesktop.layout.GroupLayout.PREFERRED_SIZE,
																49,
																org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
												.add(layout
														.createSequentialGroup()
														.add(wangwangId,
																org.jdesktop.layout.GroupLayout.PREFERRED_SIZE,
																138,
																org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
														.add(13, 13, 13)
														.add(layout
																.createParallelGroup(
																		org.jdesktop.layout.GroupLayout.LEADING)
																.add(searchButton,
																		org.jdesktop.layout.GroupLayout.PREFERRED_SIZE,
																		230,
																		org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
																.add(layout
																		.createSequentialGroup()
																		.add(label3,
																				org.jdesktop.layout.GroupLayout.PREFERRED_SIZE,
																				org.jdesktop.layout.GroupLayout.DEFAULT_SIZE,
																				org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
																		.add(22,
																				22,
																				22)
																		.add(weixinId,
																				org.jdesktop.layout.GroupLayout.PREFERRED_SIZE,
																				133,
																				org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
																		.add(51,
																				51,
																				51)
																		.add(label4,
																				org.jdesktop.layout.GroupLayout.PREFERRED_SIZE,
																				org.jdesktop.layout.GroupLayout.DEFAULT_SIZE,
																				org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
																		.add(26,
																				26,
																				26)
																		.add(mobileId,
																				org.jdesktop.layout.GroupLayout.PREFERRED_SIZE,
																				137,
																				org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)))))))
						.addContainerGap(100, Short.MAX_VALUE))
				.add(org.jdesktop.layout.GroupLayout.TRAILING,
						layout.createSequentialGroup()
								.addContainerGap(369, Short.MAX_VALUE)
								.add(label1,
										org.jdesktop.layout.GroupLayout.PREFERRED_SIZE,
										187,
										org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
								.add(332, 332, 332)));
		layout.setVerticalGroup(layout
				.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
				.add(layout
						.createSequentialGroup()
						.add(18, 18, 18)
						.add(label1,
								org.jdesktop.layout.GroupLayout.PREFERRED_SIZE,
								org.jdesktop.layout.GroupLayout.DEFAULT_SIZE,
								org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
						.add(24, 24, 24)
						.add(layout
								.createParallelGroup(
										org.jdesktop.layout.GroupLayout.LEADING,
										false)
								.add(layout
										.createSequentialGroup()
										.add(jLabel1)
										.add(34, 34, 34)
										.add(label2,
												org.jdesktop.layout.GroupLayout.PREFERRED_SIZE,
												org.jdesktop.layout.GroupLayout.DEFAULT_SIZE,
												org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
								.add(layout
										.createSequentialGroup()
										.add(layout
												.createParallelGroup(
														org.jdesktop.layout.GroupLayout.TRAILING)
												.add(excelPath,
														org.jdesktop.layout.GroupLayout.PREFERRED_SIZE,
														org.jdesktop.layout.GroupLayout.DEFAULT_SIZE,
														org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
												.add(excelpushButton,
														org.jdesktop.layout.GroupLayout.PREFERRED_SIZE,
														org.jdesktop.layout.GroupLayout.DEFAULT_SIZE,
														org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
										.addPreferredGap(
												org.jdesktop.layout.LayoutStyle.RELATED,
												29, Short.MAX_VALUE)
										.add(layout
												.createParallelGroup(
														org.jdesktop.layout.GroupLayout.LEADING)
												.add(org.jdesktop.layout.GroupLayout.TRAILING,
														wangwangId,
														org.jdesktop.layout.GroupLayout.PREFERRED_SIZE,
														org.jdesktop.layout.GroupLayout.DEFAULT_SIZE,
														org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
												.add(org.jdesktop.layout.GroupLayout.TRAILING,
														label3,
														org.jdesktop.layout.GroupLayout.PREFERRED_SIZE,
														org.jdesktop.layout.GroupLayout.DEFAULT_SIZE,
														org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
												.add(org.jdesktop.layout.GroupLayout.TRAILING,
														layout.createParallelGroup(
																org.jdesktop.layout.GroupLayout.LEADING)
																.add(weixinId,
																		org.jdesktop.layout.GroupLayout.PREFERRED_SIZE,
																		org.jdesktop.layout.GroupLayout.DEFAULT_SIZE,
																		org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
																.add(layout
																		.createParallelGroup(
																				org.jdesktop.layout.GroupLayout.TRAILING)
																		.add(mobileId,
																				org.jdesktop.layout.GroupLayout.PREFERRED_SIZE,
																				org.jdesktop.layout.GroupLayout.DEFAULT_SIZE,
																				org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
																		.add(label4,
																				org.jdesktop.layout.GroupLayout.PREFERRED_SIZE,
																				org.jdesktop.layout.GroupLayout.DEFAULT_SIZE,
																				org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))))))
						.addPreferredGap(
								org.jdesktop.layout.LayoutStyle.RELATED)
						.add(layout
								.createParallelGroup(
										org.jdesktop.layout.GroupLayout.TRAILING)
								.add(layout
										.createSequentialGroup()
										.addPreferredGap(
												org.jdesktop.layout.LayoutStyle.RELATED)
										.add(label5,
												org.jdesktop.layout.GroupLayout.PREFERRED_SIZE,
												org.jdesktop.layout.GroupLayout.DEFAULT_SIZE,
												org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
										.add(160, 160, 160))
								.add(org.jdesktop.layout.GroupLayout.LEADING,
										layout.createSequentialGroup()
												.add(24, 24, 24)
												.add(searchButton,
														org.jdesktop.layout.GroupLayout.PREFERRED_SIZE,
														org.jdesktop.layout.GroupLayout.DEFAULT_SIZE,
														org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
												.add(49, 49, 49)
												.add(showResult,
														org.jdesktop.layout.GroupLayout.PREFERRED_SIZE,
														183,
														org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
												.addPreferredGap(
														org.jdesktop.layout.LayoutStyle.RELATED)))
						.addContainerGap(85, Short.MAX_VALUE)));

		pack();
	}// </editor-fold>
	//GEN-END:initComponents

	/**
	 * @param args the command line arguments
	 */
	public static void main(String args[]) {
		java.awt.EventQueue.invokeLater(new Runnable() {
			public void run() {
				new AttJframe().setVisible(true);
			}
		});
	}

	//GEN-BEGIN:variables
	// Variables declaration - do not modify
	private java.awt.TextField excelPath;
	private java.awt.Button excelpushButton;
	private javax.swing.JLabel jLabel1;
	private java.awt.Label label1;
	private java.awt.Label label2;
	private java.awt.Label label3;
	private java.awt.Label label4;
	private java.awt.Label label5;
	private java.awt.TextField mobileId;
	private java.awt.Button searchButton;
	private java.awt.TextArea showResult;
	private java.awt.TextField wangwangId;
	private java.awt.TextField weixinId;
	// End of variables declaration//GEN-END:variables

}